// This file is AUTO-GENERATED by scripts/generate-translations-index.cjs. Do not edit manually.
// To update, run: npm run generate:translations or pnpm generate:translations

import { LOCALES as LOCALES_ar } from "./ar";
import { LOCALES as LOCALES_da } from "./da";
import { LOCALES as LOCALES_de } from "./de";
import { LOCALES as LOCALES_el } from "./el";
import { LOCALES as LOCALES_es } from "./es";
import { LOCALES as LOCALES_fa } from "./fa";
import { LOCALES as LOCALES_fr } from "./fr";
import { LOCALES as LOCALES_hi } from "./hi";
import { LOCALES as LOCALES_id } from "./id";
import { LOCALES as LOCALES_it } from "./it";
import { LOCALES as LOCALES_ja } from "./ja";
import { LOCALES as LOCALES_ko } from "./ko";
import { LOCALES as LOCALES_mr } from "./mr";
import { LOCALES as LOCALES_nl } from "./nl";
import { LOCALES as LOCALES_pl } from "./pl";
import { LOCALES as LOCALES_pt } from "./pt";
import { LOCALES as LOCALES_ru } from "./ru";
import { LOCALES as LOCALES_sv } from "./sv";
import { LOCALES as LOCALES_tr } from "./tr";
import { LOCALES as LOCALES_zh } from "./zh";

export const defaultTranslations = {
	...LOCALES_ar,
	...LOCALES_da,
	...LOCALES_de,
	...LOCALES_el,
	...LOCALES_es,
	...LOCALES_fa,
	...LOCALES_fr,
	...LOCALES_hi,
	...LOCALES_id,
	...LOCALES_it,
	...LOCALES_ja,
	...LOCALES_ko,
	...LOCALES_mr,
	...LOCALES_nl,
	...LOCALES_pl,
	...LOCALES_pt,
	...LOCALES_ru,
	...LOCALES_sv,
	...LOCALES_tr,
	...LOCALES_zh,
};
