// This file is auto-generated. Do not edit this file manually.
// To regenerate the schema, run:
// `npx @better-auth/cli generate --output undefined -y`

import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export const tables = {
	user: defineTable({
		name: v.string(),
		email: v.string(),
		emailVerified: v.boolean(),
		image: v.optional(v.union(v.null(), v.string())),
		createdAt: v.number(),
		updatedAt: v.number(),
		userId: v.optional(v.union(v.null(), v.string())),
		twoFactorEnabled: v.optional(v.union(v.null(), v.boolean())),
	})
		.index("email_name", ["email", "name"])
		.index("name", ["name"])
		.index("userId", ["userId"]),
	session: defineTable({
		expiresAt: v.number(),
		token: v.string(),
		createdAt: v.number(),
		updatedAt: v.number(),
		ipAddress: v.optional(v.union(v.null(), v.string())),
		userAgent: v.optional(v.union(v.null(), v.string())),
		userId: v.string(),
		activeOrganizationId: v.optional(v.union(v.null(), v.string())),
	})
		.index("expiresAt", ["expiresAt"])
		.index("expiresAt_userId", ["expiresAt", "userId"])
		.index("token", ["token"])
		.index("userId", ["userId"]),
	account: defineTable({
		accountId: v.string(),
		providerId: v.string(),
		userId: v.string(),
		accessToken: v.optional(v.union(v.null(), v.string())),
		refreshToken: v.optional(v.union(v.null(), v.string())),
		idToken: v.optional(v.union(v.null(), v.string())),
		accessTokenExpiresAt: v.optional(v.union(v.null(), v.number())),
		refreshTokenExpiresAt: v.optional(v.union(v.null(), v.number())),
		scope: v.optional(v.union(v.null(), v.string())),
		password: v.optional(v.union(v.null(), v.string())),
		createdAt: v.number(),
		updatedAt: v.number(),
	})
		.index("accountId", ["accountId"])
		.index("accountId_providerId", ["accountId", "providerId"])
		.index("providerId_userId", ["providerId", "userId"])
		.index("userId", ["userId"]),
	verification: defineTable({
		identifier: v.string(),
		value: v.string(),
		expiresAt: v.number(),
		createdAt: v.number(),
		updatedAt: v.number(),
	})
		.index("expiresAt", ["expiresAt"])
		.index("identifier", ["identifier"]),
	jwks: defineTable({
		publicKey: v.string(),
		privateKey: v.string(),
		createdAt: v.number(),
	}),
	organization: defineTable({
		name: v.string(),
		slug: v.optional(v.union(v.null(), v.string())),
		logo: v.optional(v.union(v.null(), v.string())),
		createdAt: v.number(),
		metadata: v.optional(v.union(v.null(), v.string())),
	})
		.index("name", ["name"])
		.index("slug", ["slug"]),
	member: defineTable({
		organizationId: v.string(),
		userId: v.string(),
		role: v.string(),
		createdAt: v.number(),
	})
		.index("organizationId_userId", ["organizationId", "userId"])
		.index("userId", ["userId"])
		.index("role", ["role"]),
	invitation: defineTable({
		organizationId: v.string(),
		email: v.string(),
		role: v.optional(v.union(v.null(), v.string())),
		status: v.string(),
		expiresAt: v.number(),
		inviterId: v.string(),
	})
		.index("email_organizationId_status", ["email", "organizationId", "status"])
		.index("organizationId_status", ["organizationId", "status"])
		.index("role", ["role"])
		.index("status", ["status"])
		.index("inviterId", ["inviterId"]),
	twoFactor: defineTable({
		secret: v.string(),
		backupCodes: v.string(),
		userId: v.string(),
	})
		.index("userId", ["userId"]),
	apikey: defineTable({
		name: v.optional(v.union(v.null(), v.string())),
		start: v.optional(v.union(v.null(), v.string())),
		prefix: v.optional(v.union(v.null(), v.string())),
		key: v.string(),
		userId: v.string(),
		refillInterval: v.optional(v.union(v.null(), v.number())),
		refillAmount: v.optional(v.union(v.null(), v.number())),
		lastRefillAt: v.optional(v.union(v.null(), v.number())),
		enabled: v.optional(v.union(v.null(), v.boolean())),
		rateLimitEnabled: v.optional(v.union(v.null(), v.boolean())),
		rateLimitTimeWindow: v.optional(v.union(v.null(), v.number())),
		rateLimitMax: v.optional(v.union(v.null(), v.number())),
		requestCount: v.optional(v.union(v.null(), v.number())),
		remaining: v.optional(v.union(v.null(), v.number())),
		lastRequest: v.optional(v.union(v.null(), v.number())),
		expiresAt: v.optional(v.union(v.null(), v.number())),
		createdAt: v.number(),
		updatedAt: v.number(),
		permissions: v.optional(v.union(v.null(), v.string())),
		metadata: v.optional(v.union(v.null(), v.string())),
	})
		.index("key", ["key"])
		.index("userId", ["userId"]),
	deviceCode: defineTable({
		deviceCode: v.string(),
		userCode: v.string(),
		userId: v.optional(v.union(v.null(), v.string())),
		expiresAt: v.number(),
		status: v.string(),
		lastPolledAt: v.optional(v.union(v.null(), v.number())),
		pollingInterval: v.optional(v.union(v.null(), v.number())),
		clientId: v.optional(v.union(v.null(), v.string())),
		scope: v.optional(v.union(v.null(), v.string())),
	}),
	auditLogs: defineTable({
		userId: v.string(),
		action: v.string(),
		timestamp: v.string(),
		ipAddress: v.string(),
		userAgent: v.string(),
		severity: v.union(v.literal("info"), v.literal("warning"), v.literal("error"), v.literal("severe")),
		type: v.union(v.literal("authentication"), v.literal("authorization"), v.literal("api"), v.literal("unknown"))
	})
		.index("by_user_timestamp", ["userId", "timestamp"])
		.index("by_user_action", ["userId", "action"])
		.index("by_user_type", ["userId", "type"])
		.index("by_user_severity", ["userId", "severity"])
		.index("by_user_type_severity_timestamp", ["userId", "type", "severity", "timestamp"])
};

const schema = defineSchema(tables);

export default schema;
